server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/study

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.rt.generalframework.entity

logging:
  level:
    com:
      rt:
        generalframework:
          mapper: debug

























