#英文字符集时开启
#spring.datasource.druid.connection-properties=clientEncoding=GBK;serverEncoding=ISO-8859-1;
#如果是mysql打开下面两行配置
#spring.datasource.druid.validation-query: SELECT 1
#spring.datasource.druid.filter.stat.db-type: mysql
#数据源配置
#spring.datasource.druid.driver-class-name: com.mysql.jdbc.Driver
#spring.datasource.druid.url: jdbc:mysql://192.168.0.118:3306/base_sys?useUnicode=true&characterEncoding=utf8&useSSL=false
spring.datasource.druid.driver-class-name: oracle.jdbc.OracleDriver
spring.datasource.druid.url: jdbc:oracle:thin:@192.168.0.118:1521/spacs
spring.datasource.druid.username: RTCODER@63OSeGsi7ScESkzOcTIPZh3dCr1eYGnE
spring.datasource.druid.password: RTCODER@63OSeGsi7ScESkzOcTIPZh3dCr1eYGnE
#设置项目名和端口
server.servlet.context-path: /general
server.port: 8080